#!/usr/bin/env bun
/**
 * Codegen for the Bun single-binary build. Walks the built UI output
 * (`packages/cli/dist/ui/client`) and writes
 * `packages/cli/src/generated/embedded-assets.ts` with one
 * `import … with { type: "file" }` per asset plus a URL-path -> path map.
 *
 * `bun build --compile` embeds every file imported this way; at runtime the
 * imported value is a path that `Bun.file()` resolves to the embedded blob.
 *
 * Only run as part of `scripts/build-bun.ts`. The generated file is Bun-only
 * (Node rejects the `type: "file"` import attribute) and git-ignored.
 */
import './lib/require-bun.ts';
import {
  readdirSync,
  statSync,
  mkdirSync,
  writeFileSync,
  existsSync,
} from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const clientDir = join(root, 'packages/cli/dist/ui/client');
const outFile = join(
  root,
  'packages/cli/src/generated/embedded-assets.ts',
);

if (!existsSync(clientDir)) {
  console.error(
    `UI build not found at ${clientDir} — run \`npm run build\` first.`,
  );
  process.exit(1);
}

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full));
    } else {
      out.push(full);
    }
  }
  return out;
}

const files = walk(clientDir).sort();
const lines: string[] = [
  '// AUTO-GENERATED by scripts/gen-embedded-assets.ts — do not edit.',
  '/* eslint-disable */',
];
const mapEntries: string[] = [];

files.forEach((abs, i) => {
  const rel = relative(clientDir, abs).split('\\').join('/');
  const urlPath = `/${rel}`;
  const spec = abs.split('\\').join('/');
  lines.push(`import a${i} from ${JSON.stringify(spec)} with { type: 'file' };`);
  mapEntries.push(`  ${JSON.stringify(urlPath)}: a${i},`);
});

lines.push('');
lines.push('export const EMBEDDED_ASSETS: Record<string, string> = {');
lines.push(...mapEntries);
lines.push('};');
lines.push('');

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join('\n'));
console.log(`Embedded ${files.length} UI assets -> ${relative(root, outFile)}`);
